// ═══════════════════════════════════════════════════════════
//  CURSE DATA  (wiki-sourced)
//  img: filename on static.wikitide.net/nullscapewiki/
//  value: altar of purification priority score (higher = removed first)
//  enemy: which enemy type this curse is tied to (null = global)
// ═══════════════════════════════════════════════════════════
const CURSES = [
    // ── Global ────────────────────────────────────────────
    {
        name: 'LAP 2',
        img: 'LAP2.png',
        value: 400,
        cat: 'global',
        enemy: null,
        minLvl: 8,
        maxStack: 1,
        altText: '+25% Golden Gift yield, slower collapse, beacon requires 40% of total gifts. Some multipliers nerfed.',
        effect: 'Increases gift yield by +25%. Slows the collapse speed. Beacon requires 40% of total Golden Gifts collected before spawning. Altar of Purgatory yield divided by 1.5.',
    },
    {
        name: 'Nothing?',
        img: 'Nothing%3F.png',
        value: 325,
        cat: 'global',
        enemy: null,
        minLvl: 8,
        maxStack: 1,
        altText: 'Shops are +15% cheaper. No Downsides!',
        effect: 'Shops cost 15% less. However, adds 1 hidden enemy per 5 levels, scaling up to 8 max. Enemies are not shown in the top bar.',
    },
    {
        name: 'Beacon Mirage',
        img: 'BeaconMirage.png',
        value: 300,
        cat: 'global',
        enemy: null,
        minLvl: 5,
        maxStack: 1,
        altText: 'There will be fake beacons. Only one is real.',
        effect: 'Fake beacons appear alongside the real one. Players must identify the correct beacon to finish the level.',
    },
    {
        name: 'Fragile Gifts',
        img: 'FragileGifts.png',
        value: 280,
        cat: 'global',
        enemy: null,
        minLvl: 5,
        maxStack: 1,
        altText: 'Gifts shatter if collected too quickly.',
        effect: 'Collecting gifts too fast causes them to shatter, granting no reward. Mutually exclusive with LAP 2.',
    },
    {
        name: 'Jackpot',
        img: 'Jackpot.png',
        value: 250,
        cat: 'global',
        enemy: null,
        minLvl: 5,
        maxStack: 1,
        altText: 'Gift yields are completely randomized.',
        effect: 'All Golden Gift yields are replaced with a random amount per gift collected.',
    },
    {
        name: 'Lower Gravity',
        img: 'LowerGravity.png',
        value: 200,
        cat: 'global',
        enemy: null,
        minLvl: 1,
        maxStack: 1,
        altText: 'Gravity is significantly reduced.',
        effect: 'All players experience lower gravity, affecting jumping, falling, and jump pad trajectory.',
    },
    {
        name: 'Minefield',
        img: 'Minefield.png',
        value: 200,
        cat: 'global',
        enemy: null,
        minLvl: 10,
        maxStack: 1,
        altText: 'Mines are scattered throughout the level.',
        effect: 'Hidden mines are placed across the level. Stepping on one triggers an explosion.',
    },
    {
        name: 'Barotrauma',
        img: 'Barotrauma.png',
        value: 175,
        cat: 'global',
        enemy: null,
        minLvl: 5,
        maxStack: 1,
        altText: 'Losing altitude rapidly deals damage.',
        effect: 'Players take damage when descending quickly. Staying high up is critical.',
    },
    {
        name: 'Random Spawn',
        img: 'RandomSpawn.png',
        value: 150,
        cat: 'global',
        enemy: null,
        minLvl: 1,
        maxStack: 1,
        altText: 'Players spawn at random locations.',
        effect: 'Every round, players are spawned at random positions across the map instead of designated spawn points.',
    },
    {
        name: 'Scattered Gifts',
        img: 'ScatteredGifts.png',
        value: 150,
        cat: 'global',
        enemy: null,
        minLvl: 1,
        maxStack: 1,
        altText: 'Gifts are spread further across the map.',
        effect: 'Golden Gifts are placed much further apart, making collection runs longer.',
    },
    {
        name: 'Weaker Jump Pads',
        img: 'WeakerJumpPads.png',
        value: 125,
        cat: 'global',
        enemy: null,
        minLvl: 1,
        maxStack: 1,
        altText: 'Jump pads launch players with less force.',
        effect: 'All jump pads in the level have reduced launch power.',
    },
    {
        name: 'High Roller',
        img: 'HighRoller.png',
        value: 120,
        cat: 'global',
        enemy: null,
        minLvl: 3,
        maxStack: 1,
        altText: 'Curse shop re-rolls cost more.',
        effect: 'Re-rolling curse options in the curse shop costs significantly more Golden Gifts.',
    },
    {
        name: 'Tweaked Odds',
        img: 'TweakedOdds.png',
        value: 100,
        cat: 'global',
        enemy: null,
        minLvl: 3,
        maxStack: 1,
        altText: 'Upgrade shop selection is randomized differently.',
        effect: 'The upgrade shop offers a different randomized pool of items than normal.',
    },
    {
        name: 'Fake Count',
        img: 'FakeCount.png',
        value: 100,
        cat: 'global',
        enemy: null,
        minLvl: 3,
        maxStack: 1,
        altText: 'The gift counter shows wrong numbers.',
        effect: 'The Golden Gift collection counter displays incorrect numbers, making it hard to track progress.',
    },
    {
        name: 'Savory Ring',
        img: 'SavoryRing.png',
        value: 80,
        cat: 'global',
        enemy: null,
        minLvl: 1,
        maxStack: 1,
        altText: 'Swiftness Ring has no effect.',
        effect: 'The Swiftness Ring upgrade is completely negated — speed bonuses are removed.',
    },
    {
        name: 'Bigger Tripmines',
        img: 'BiggerTripmines.png',
        value: 80,
        cat: 'global',
        enemy: null,
        minLvl: 1,
        maxStack: 1,
        altText: 'Tripmines have a larger explosion radius.',
        effect: 'All tripmines in the level have a significantly increased blast radius.',
    },
    {
        name: 'More Tripmines',
        img: 'MoreTripmines.png',
        value: 60,
        cat: 'global',
        enemy: null,
        minLvl: 1,
        maxStack: 3,
        altText: 'More tripmines are placed per level.',
        effect: 'Additional tripmines are spawned across the level each round.',
    },

    // ── Enemy: Bell ────────────────────────────────────────
    {
        name: 'More Ringing',
        img: 'MoreRinging.png',
        value: 120,
        cat: 'enemy',
        enemy: 'Bell',
        minLvl: 1,
        maxStack: 1,
        altText: 'Bells ring more frequently.',
        effect: 'Bell enemies ring at a much higher rate, increasing danger for nearby players.',
    },
    {
        name: 'Mighty Gong',
        img: 'MightyGong.png',
        value: 150,
        cat: 'enemy',
        enemy: 'Bell',
        minLvl: 1,
        maxStack: 1,
        altText: 'Bell rings send out a powerful shockwave.',
        effect: 'When a Bell rings, it emits a powerful shockwave that deals significant knockback and damage.',
    },
    {
        name: 'Concussion',
        img: 'Concussion.png',
        value: 140,
        cat: 'enemy',
        enemy: 'Bell',
        minLvl: 1,
        maxStack: 1,
        altText: 'Bell rings stun nearby players.',
        effect: 'Players within range of a Bell ring are briefly stunned, unable to move or act.',
    },

    // ── Enemy: Mart ────────────────────────────────────────
    {
        name: 'Bigger Marts',
        img: 'BiggerMarts.png',
        value: 100,
        cat: 'enemy',
        enemy: 'Mart',
        minLvl: 1,
        maxStack: 1,
        altText: 'Mart enemies are larger.',
        effect: 'All Mart enemies spawn at a larger size, making them harder to dodge in tight spaces.',
    },
    {
        name: 'Mart Infection',
        img: 'MartInfection.png',
        value: 200,
        cat: 'enemy',
        enemy: 'Mart',
        minLvl: 5,
        maxStack: 1,
        altText: 'Marts infect players on contact, slowing them.',
        effect: 'Contact with a Mart enemy infects the player, applying a movement-slowing debuff for several seconds.',
    },
    {
        name: 'Mart Slide',
        img: 'MartSlide.png',
        value: 330,
        cat: 'enemy',
        enemy: 'Mart',
        minLvl: 1,
        maxStack: 1,
        altText: 'Mart enemies slide at high speed.',
        effect: 'Mart enemies slide across the floor at greatly increased speed, making them very hard to avoid.',
    },

    // ── Enemy: Baby ────────────────────────────────────────
    {
        name: 'Pacifier',
        img: 'Pacifier.png',
        value: 130,
        cat: 'enemy',
        enemy: 'Baby',
        minLvl: 1,
        maxStack: 1,
        altText: 'Baby enemies calm down slower.',
        effect: 'Baby enemies take longer to calm after being struck, remaining enraged for extended periods.',
    },
    {
        name: 'Problem Child',
        img: 'ProblemChild.png',
        value: 160,
        cat: 'enemy',
        enemy: 'Baby',
        minLvl: 3,
        maxStack: 1,
        altText: 'Babies become enraged more often.',
        effect: 'Baby enemies become enraged much more frequently and unpredictably.',
    },

    // ── Enemy: ICBM ────────────────────────────────────────
    {
        name: 'Scorched Earth',
        img: 'ScorchedEarth.png',
        value: 180,
        cat: 'enemy',
        enemy: 'ICBM',
        minLvl: 5,
        maxStack: 1,
        altText: 'ICBM explosions leave fire on the ground.',
        effect: 'When an ICBM explodes, it leaves a patch of lingering fire that damages players who walk through it.',
    },
    {
        name: 'Bigger Blast',
        img: 'BiggerBlast.png',
        value: 150,
        cat: 'enemy',
        enemy: 'ICBM',
        minLvl: 3,
        maxStack: 1,
        altText: 'ICBM explosions have a larger radius.',
        effect: 'ICBM explosion radius is significantly increased, making them much harder to dodge.',
    },

    // ── Enemy: Husk ────────────────────────────────────────
    {
        name: 'Closer Husk',
        img: 'CloserHusk.png',
        value: 80,
        cat: 'enemy',
        enemy: 'Husk',
        minLvl: 1,
        maxStack: 1,
        altText: 'Husks activate at a closer range.',
        effect: 'Husks trigger when players approach from a shorter distance than usual.',
    },
    {
        name: 'Further Husk',
        img: 'FurtherHusk.png',
        value: 80,
        cat: 'enemy',
        enemy: 'Husk',
        minLvl: 1,
        maxStack: 1,
        altText: 'Husks activate at a further range.',
        effect: 'Husks have extended detection range and trigger from much further away.',
    },
    {
        name: 'Taller Husk',
        img: 'TallerHusk.png',
        value: 90,
        cat: 'enemy',
        enemy: 'Husk',
        minLvl: 1,
        maxStack: 1,
        altText: 'Husks are taller.',
        effect: 'Husk enemies spawn at greater height, covering more vertical space.',
    },
    {
        name: 'Husk Express',
        img: 'HuskExpress.png',
        value: 140,
        cat: 'enemy',
        enemy: 'Husk',
        minLvl: 3,
        maxStack: 1,
        altText: 'Husks move much faster.',
        effect: 'Husks move at significantly increased speed once activated, making them very hard to outrun.',
    },
    {
        name: 'Conga Line',
        img: 'CongaLine.png',
        value: 120,
        cat: 'enemy',
        enemy: 'Husk',
        minLvl: 3,
        maxStack: 1,
        altText: 'Multiple husks chain together.',
        effect: 'Husks connect in a chain, so activating one pulls the entire conga line into motion simultaneously.',
    },
    {
        name: 'Random Husk',
        img: 'RandomHusk.png',
        value: 100,
        cat: 'enemy',
        enemy: 'Husk',
        minLvl: 1,
        maxStack: 1,
        altText: 'Husks spawn in random positions.',
        effect: 'Husks are placed at random locations each round instead of fixed positions.',
    },

    // ── Enemy: Springer ────────────────────────────────────
    {
        name: 'Resonating Shockwaves',
        img: 'ResonatingShockwaves.png',
        value: 170,
        cat: 'enemy',
        enemy: 'Springer',
        minLvl: 5,
        maxStack: 1,
        altText: 'Springer shockwaves last longer.',
        effect: 'Shockwaves generated by Springer enemies persist on the ground for a longer duration.',
    },
    {
        name: 'Springloaded',
        img: 'Springloaded.png',
        value: 140,
        cat: 'enemy',
        enemy: 'Springer',
        minLvl: 3,
        maxStack: 1,
        altText: 'Springers launch more frequently.',
        effect: 'Springer enemies launch their attacks far more often, increasing the frequency of shockwaves.',
    },

    // ── Enemy: Flesh ────────────────────────────────────────
    {
        name: 'Bloodier Meat',
        img: 'BloodierMeat.png',
        value: 300,
        cat: 'enemy',
        enemy: 'Flesh',
        minLvl: 1,
        maxStack: 1,
        altText: 'Flesh enemies are more aggressive.',
        effect: 'Flesh enemies deal more damage and move more aggressively toward players.',
    },
    {
        name: 'Blighted Jump Pads',
        img: 'BlightedJumpPads.png',
        value: 150,
        cat: 'enemy',
        enemy: 'Flesh',
        minLvl: 3,
        maxStack: 1,
        altText: 'Jump pads near Flesh enemies are corrupted.',
        effect: 'Jump pads in proximity to Flesh enemies become blighted, sending players in unpredictable directions.',
    },

    // ── Enemy: Guardian ────────────────────────────────────
    {
        name: 'Camouflage',
        img: 'Camouflage.png',
        value: 160,
        cat: 'enemy',
        enemy: 'Guardian',
        minLvl: 5,
        maxStack: 1,
        altText: 'Guardians become temporarily invisible.',
        effect: 'Guardian enemies periodically turn invisible, making them extremely difficult to track.',
    },
    {
        name: 'Shotgun',
        img: 'Shotgun.png',
        value: 200,
        cat: 'enemy',
        enemy: 'Guardian',
        minLvl: 5,
        maxStack: 1,
        altText: 'Guardians fire in a spread pattern.',
        effect: 'Guardian projectile attacks spread in a shotgun pattern, covering a wide area.',
    },

    // ── Enemy: Telefragger ────────────────────────────────
    {
        name: 'Ambush',
        img: 'Ambush.png',
        value: 180,
        cat: 'enemy',
        enemy: 'Telefragger',
        minLvl: 5,
        maxStack: 1,
        altText: 'Telefraggers teleport behind players.',
        effect: 'Telefraggers now always teleport directly behind their target before attacking.',
    },
    {
        name: 'Accurate Telefragger',
        img: 'AccurateTelefragger.png',
        value: 200,
        cat: 'enemy',
        enemy: 'Telefragger',
        minLvl: 8,
        maxStack: 1,
        altText: 'Telefraggers have perfect accuracy.',
        effect: 'Telefragger attacks are perfectly accurate and cannot miss.',
    },

    // ── Enemy: Kolóna ──────────────────────────────────────
    {
        name: 'Lost Embers',
        img: 'LostEmbers.png',
        value: 150,
        cat: 'enemy',
        enemy: 'Kolóna',
        minLvl: 3,
        maxStack: 1,
        altText: 'Kolóna leaves damaging embers behind.',
        effect: 'Kolóna enemies leave a trail of burning embers that linger and damage players who touch them.',
    },
    {
        name: 'Burning Bouquet',
        img: 'BurningBouquet.png',
        value: 180,
        cat: 'enemy',
        enemy: 'Kolóna',
        minLvl: 5,
        maxStack: 1,
        altText: 'Kolóna bouquets ignite players.',
        effect: 'The bouquets thrown by Kolóna enemies set players on fire, applying a burn damage over time.',
    },

    // ── Enemy: Voidbreaker ────────────────────────────────
    {
        name: 'Blade Carousel',
        img: 'BladeCarousel.png',
        value: 220,
        cat: 'enemy',
        enemy: 'Voidbreaker',
        minLvl: 8,
        maxStack: 1,
        altText: 'Voidbreaker spins blades around itself.',
        effect: 'The Voidbreaker enemy continuously spins a ring of blades around it, creating a larger danger zone.',
    },

    // ── Enemy: Cadence ────────────────────────────────────
    {
        name: 'Deadly Melody',
        img: 'DeadlyMelody.png',
        value: 240,
        cat: 'enemy',
        enemy: 'Cadence',
        minLvl: 10,
        maxStack: 1,
        altText: "Cadence's attacks deal greatly increased damage.",
        effect: 'Cadence enemy attacks deal significantly more damage per hit.',
    },
];

// ═══════════════════════════════════════════════════════════
//  IMG URL MAP  (hashes verified via MediaWiki API)
// ═══════════════════════════════════════════════════════════
const IMG = {
    'LAP2.png': 'https://static.wikitide.net/nullscapewiki/1/1f/LAP2.png',
    'Nothing%3F.png': 'https://static.wikitide.net/nullscapewiki/a/a9/Nothing%3F.png',
    'BeaconMirage.png': 'https://static.wikitide.net/nullscapewiki/0/0a/BeaconMirage.png',
    'FragileGifts.png': 'https://static.wikitide.net/nullscapewiki/4/42/FragileGifts.png',
    'Jackpot.png': 'https://static.wikitide.net/nullscapewiki/1/10/Jackpot.png',
    'LowerGravity.png': 'https://static.wikitide.net/nullscapewiki/3/3a/LowerGravity.png',
    'Minefield.png': 'https://static.wikitide.net/nullscapewiki/3/32/Minefield.png',
    'Barotrauma.png': 'https://static.wikitide.net/nullscapewiki/e/e5/Barotrauma.png',
    'RandomSpawn.png': 'https://static.wikitide.net/nullscapewiki/c/c1/RandomSpawn.png',
    'ScatteredGifts.png': 'https://static.wikitide.net/nullscapewiki/2/27/ScatteredGifts.png',
    'WeakerJumpPads.png': 'https://static.wikitide.net/nullscapewiki/d/df/WeakerJumpPads.png',
    'HighRoller.png': 'https://static.wikitide.net/nullscapewiki/6/6b/HighRoller.png',
    'TweakedOdds.png': 'https://static.wikitide.net/nullscapewiki/9/93/TweakedOdds.png',
    'FakeCount.png': 'https://static.wikitide.net/nullscapewiki/c/c8/FakeCount.png',
    'SavoryRing.png': 'https://static.wikitide.net/nullscapewiki/b/b6/SavoryRing.png',
    'BiggerTripmines.png': 'https://static.wikitide.net/nullscapewiki/3/38/BiggerTripmines.png',
    'MoreTripmines.png': 'https://static.wikitide.net/nullscapewiki/8/85/MoreTripmines.png',
    'MoreRinging.png': 'https://static.wikitide.net/nullscapewiki/5/5e/MoreRinging.png',
    'MightyGong.png': 'https://static.wikitide.net/nullscapewiki/0/07/MightyGong.png',
    'Concussion.png': 'https://static.wikitide.net/nullscapewiki/1/10/Concussion.png',
    'BiggerMarts.png': 'https://static.wikitide.net/nullscapewiki/1/11/BiggerMarts.png',
    'MartInfection.png': 'https://static.wikitide.net/nullscapewiki/1/16/MartInfection.png',
    'MartSlide.png': 'https://static.wikitide.net/nullscapewiki/3/33/MartSlide.png',
    'Pacifier.png': 'https://static.wikitide.net/nullscapewiki/2/2a/Pacifier.png',
    'ProblemChild.png': 'https://static.wikitide.net/nullscapewiki/7/79/ProblemChild.png',
    'ScorchedEarth.png': 'https://static.wikitide.net/nullscapewiki/c/c6/ScorchedEarth.png',
    'BiggerBlast.png': 'https://static.wikitide.net/nullscapewiki/3/38/BiggerBlast.png',
    'CloserHusk.png': 'https://static.wikitide.net/nullscapewiki/9/9f/CloserHusk.png',
    'FurtherHusk.png': 'https://static.wikitide.net/nullscapewiki/2/23/FurtherHusk.png',
    'TallerHusk.png': 'https://static.wikitide.net/nullscapewiki/0/01/TallerHusk.png',
    'HuskExpress.png': 'https://static.wikitide.net/nullscapewiki/8/87/HuskExpress.png',
    'CongaLine.png': 'https://static.wikitide.net/nullscapewiki/e/e1/CongaLine.png',
    'RandomHusk.png': 'https://static.wikitide.net/nullscapewiki/6/6d/RandomHusk.png',
    'ResonatingShockwaves.png': 'https://static.wikitide.net/nullscapewiki/9/9c/ResonatingShockwaves.png',
    'Springloaded.png': 'https://static.wikitide.net/nullscapewiki/a/a0/Springloaded.png',
    'BloodierMeat.png': 'https://static.wikitide.net/nullscapewiki/b/b1/BloodierMeat.png',
    'BlightedJumpPads.png': 'https://static.wikitide.net/nullscapewiki/f/f9/BlightedJumpPads.png',
    'Camouflage.png': 'https://static.wikitide.net/nullscapewiki/9/9e/Camouflage.png',
    'Shotgun.png': 'https://static.wikitide.net/nullscapewiki/6/61/Shotgun.png',
    'Ambush.png': 'https://static.wikitide.net/nullscapewiki/3/30/Ambush.png',
    'AccurateTelefragger.png': 'https://static.wikitide.net/nullscapewiki/c/c0/AccurateTelefragger.png',
    'LostEmbers.png': 'https://static.wikitide.net/nullscapewiki/0/0f/LostEmbers.png',
    'BurningBouquet.png': 'https://static.wikitide.net/nullscapewiki/7/75/BurningBouquet.png',
    'BladeCarousel.png': 'https://static.wikitide.net/nullscapewiki/8/8b/BladeCarousel.png',
    'DeadlyMelody.png': 'https://static.wikitide.net/nullscapewiki/2/22/DeadlyMelody.png',
};

function imgUrl(filename) {
    return IMG[filename] || '';
}
